language: android
os: linux
dist: trusty

jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_COMPILE_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=29.0.2

android:
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_COMPILE_API_LEVEL
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-x86-android-28
    #    - sys-img-armeabi-v7a-android-28

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-30"
  - yes | sdkmanager "build-tools;29.0.2"

script:
  - ./gradlew :cloudsdk:assembleDebug :cloudsdk:testDebugUnitTest :cloudsdk:jacocoTestReport 
  - ./gradlew :cloudsdk:coveralls

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native/
    - $HOME/.gradle/daemon/native/

